<?php

    namespace Meeshalk\GloERSWebServiceSdk;

    use Meeshalk\GloERSWebServiceSdk\Type;
    use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMap;
    use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMapCollection;

    class GloERSClassmap
    {

        public static function getCollection(): ClassMapCollection
        {
            return new ClassMapCollection(
                new ClassMap('customOperation', Type\CustomOperation::class),
                new ClassMap('clientContext', Type\ClientContext::class),
                new ClassMap('principalId', Type\PrincipalId::class),
                new ClassMap('mapArray', Type\MapArray::class),
                new ClassMap('parameter', Type\Parameter::class),
                new ClassMap('principalAccountSpecifier', Type\PrincipalAccountSpecifier::class),
                new ClassMap('ersMap', Type\ErsMap::class),
                new ClassMap('customOperationResponse', Type\CustomOperationResponse::class),
                new ClassMap('ERSWSResponse', Type\ERSWSResponse::class),
                new ClassMap('ERSCommitTopupResponse', Type\ERSCommitTopupResponse::class),
                new ClassMap('principal', Type\Principal::class),
                new ClassMap('accounts', Type\Accounts::class),
                new ClassMap('principalAccount', Type\PrincipalAccount::class),
                new ClassMap('amount', Type\Amount::class),
                new ClassMap('ERSCancelTopupResponse', Type\ERSCancelTopupResponse::class),
                new ClassMap('ERSWSGetVouchersDenominationResponse', Type\ERSWSGetVouchersDenominationResponse::class),
                new ClassMap('voucherProduct', Type\VoucherProduct::class),
                new ClassMap('ERSWSExecuteReportResponse', Type\ERSWSExecuteReportResponse::class),
                new ClassMap('report', Type\Report::class),
                new ClassMap('ERSWSPrincipalInformationResponse', Type\ERSWSPrincipalInformationResponse::class),
                new ClassMap('ERSWSTopupResponse', Type\ERSWSTopupResponse::class),
                new ClassMap('ERSWSPurchaseResponse', Type\ERSWSPurchaseResponse::class),
                new ClassMap('purchaseOrderResultRow', Type\PurchaseOrderResultRow::class),
                new ClassMap('purchaseOrderRow', Type\PurchaseOrderRow::class),
                new ClassMap('productDetail', Type\ProductDetail::class),
                new ClassMap('map', Type\Map::class),
                new ClassMap('entry', Type\Entry::class),
                new ClassMap('productSpecifier', Type\ProductSpecifier::class),
                new ClassMap('cancelPurchaseOrderRow', Type\CancelPurchaseOrderRow::class),
                new ClassMap('cancelPurchaseOrderResultRow', Type\CancelPurchaseOrderResultRow::class),
                new ClassMap('ERSWSDeActivateResellerResponse', Type\ERSWSDeActivateResellerResponse::class),
                new ClassMap('ERSWSActivateResellerResponse', Type\ERSWSActivateResellerResponse::class),
                new ClassMap('ERSWSGetTransactionStatusResponse', Type\ERSWSGetTransactionStatusResponse::class),
                new ClassMap('ERSWSUpdateResellerResponse', Type\ERSWSUpdateResellerResponse::class),
                new ClassMap('ERSWSBlockResellerResponse', Type\ERSWSBlockResellerResponse::class),
                new ClassMap('ERSWSUnBlockResellerResponse', Type\ERSWSUnBlockResellerResponse::class),
                new ClassMap('ERSWSFreezeResellerResponse', Type\ERSWSFreezeResellerResponse::class),
                new ClassMap('ERSWSUnFreezeResellerResponse', Type\ERSWSUnFreezeResellerResponse::class),
                new ClassMap('ERSWSLinkSubResellerResponse', Type\ERSWSLinkSubResellerResponse::class),
                new ClassMap('ERSWSDeLinkSubResellerResponse', Type\ERSWSDeLinkSubResellerResponse::class),
                new ClassMap('ERSWSCancelPurchaseResponse', Type\ERSWSCancelPurchaseResponse::class),
                new ClassMap('ERSWSTransferResponse', Type\ERSWSTransferResponse::class),
                new ClassMap('ERSWSRegisterSubResellerResponse', Type\ERSWSRegisterSubResellerResponse::class),
                new ClassMap('deLinkSubReseller', Type\DeLinkSubReseller::class),
                new ClassMap('deLinkSubResellerResponse', Type\DeLinkSubResellerResponse::class),
                new ClassMap('registerSubReseller', Type\RegisterSubReseller::class),
                new ClassMap('registerSubResellerResponse', Type\RegisterSubResellerResponse::class),
                new ClassMap('getTransactionStatus', Type\GetTransactionStatus::class),
                new ClassMap('getTransactionStatusResponse', Type\GetTransactionStatusResponse::class),
                new ClassMap('requestPrincipalInformation', Type\RequestPrincipalInformation::class),
                new ClassMap('requestPrincipalInformationResponse', Type\RequestPrincipalInformationResponse::class),
                new ClassMap('requestTopup', Type\RequestTopup::class),
                new ClassMap('requestTopupResponse', Type\RequestTopupResponse::class),
                new ClassMap('requestTransfer', Type\RequestTransfer::class),
                new ClassMap('requestTransferResponse', Type\RequestTransferResponse::class),
                new ClassMap('cancelPurchase', Type\CancelPurchase::class),
                new ClassMap('cancelPurchaseResponse', Type\CancelPurchaseResponse::class),
                new ClassMap('unFreezeReseller', Type\UnFreezeReseller::class),
                new ClassMap('targetPrincipal', Type\TargetPrincipal::class),
                new ClassMap('unFreezeResellerResponse', Type\UnFreezeResellerResponse::class),
                new ClassMap('freezeReseller', Type\FreezeReseller::class),
                new ClassMap('freezeResellerResponse', Type\FreezeResellerResponse::class),
                new ClassMap('linkSubReseller', Type\LinkSubReseller::class),
                new ClassMap('linkSubResellerResponse', Type\LinkSubResellerResponse::class),
                new ClassMap('unBlockReseller', Type\UnBlockReseller::class),
                new ClassMap('unBlockResellerResponse', Type\UnBlockResellerResponse::class),
                new ClassMap('getVouchersDenomination', Type\GetVouchersDenomination::class),
                new ClassMap('getVouchersDenominationResponse', Type\GetVouchersDenominationResponse::class),
                new ClassMap('requestPurchase', Type\RequestPurchase::class),
                new ClassMap('requestPurchaseResponse', Type\RequestPurchaseResponse::class),
                new ClassMap('updateReseller', Type\UpdateReseller::class),
                new ClassMap('updateResellerParams', Type\UpdateResellerParams::class),
                new ClassMap('addressData', Type\AddressData::class),
                new ClassMap('personData', Type\PersonData::class),
                new ClassMap('updateResellerResponse', Type\UpdateResellerResponse::class),
                new ClassMap('deActivateReseller', Type\DeActivateReseller::class),
                new ClassMap('deActivateResellerResponse', Type\DeActivateResellerResponse::class),
                new ClassMap('activateReseller', Type\ActivateReseller::class),
                new ClassMap('activateResellerResponse', Type\ActivateResellerResponse::class),
                new ClassMap('executeReport', Type\ExecuteReport::class),
                new ClassMap('parameterMap', Type\ParameterMap::class),
                new ClassMap('executeReportResponse', Type\ExecuteReportResponse::class),
                new ClassMap('blockReseller', Type\BlockReseller::class),
                new ClassMap('blockResellerResponse', Type\BlockResellerResponse::class),
                new ClassMap('changePrincipalPassword', Type\ChangePrincipalPassword::class),
                new ClassMap('changePrincipalPasswordResponse', Type\ChangePrincipalPasswordResponse::class),
                new ClassMap('invoice', Type\Invoice::class),
                new ClassMap('invoiceRows', Type\InvoiceRows::class),
                new ClassMap('paymentInvoiceRow', Type\PaymentInvoiceRow::class),
                new ClassMap('customerToken', Type\CustomerToken::class),
                new ClassMap('clientTransactionData', Type\ClientTransactionData::class),
                new ClassMap('cancelTopupResponse', Type\CancelTopupResponse::class),
                new ClassMap('commitTopup', Type\CommitTopup::class),
                new ClassMap('commitTopupResponse', Type\CommitTopupResponse::class),
                new ClassMap('redeemVoucher', Type\RedeemVoucher::class),
                new ClassMap('redeemVoucherResponse', Type\RedeemVoucherResponse::class),
                new ClassMap('requestCancelTopup', Type\RequestCancelTopup::class),
            );
        }
    }

